fix: Make sure token creation has the needed inputs (#26)
The node upgrade workflow is currently failing with:
```
Error: [@octokit/auth-app] appId option is required
```

See
https://github.com/cdktn-io/cdktn-provider-project/actions/runs/26435816438/job/77818361817

I believe this is the result of trying to reference environment
variables that haven't been set.
This PR bypasses the environment variables and just references the
secrets directly to keep things simple.